name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Execute dry run
        required: true
        type: boolean
        default: false

jobs:
  release-dry-run:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == '3liz' && inputs.dry_run == true}}
    steps:
      - uses: actions/checkout@v6

      - name: Fetch yapt
        run: |
          curl ${{ vars.YAPT_REPOSITORY_URL }} | tar -xzf -
      
      - name: Fetch current changelog
        run: |
          ./yapt-pkg changelog >> release.md
          cat release.md

      - name: Package and deploy the zip
        run: >
          ./yapt-pkg -v package

  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == '3liz' && inputs.dry_run == false }}

    steps:
      - uses: actions/checkout@v6
      
      - name: Fetch yapt
        run: curl ${{ vars.YAPT_REPOSITORY_URL }} | tar -xzf -
      
      - name: Fetch current changelog
        run: |
          ./yapt-pkg changelog >> release.md
          cat release.md

      - name: Package
        run: >
          ./yapt-pkg -v package

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.20.0
        with:
          bodyFile: release.md
          artifacts: "*.zip"
          token: ${{ secrets.BOT_HUB_TOKEN }}

